export const COMMAND_HELPER_LABELS = {
  title: '命令助手',
  readMore: '查看更多',
  arguments: '参数：',
  usage: '用法说明：',
  examples: '示例：',
  since: '始于：',
  complexity: '复杂度：',
  defaultScreen: '在 CLI 中输入命令，或使用搜索查看详细信息。',
  searchPlaceholder: '搜索命令',
  noResults: '未找到结果。',
  required: '必填',
  optional: '可选',
  multiple: '多个',
  cli: 'CLI',
  profiler: '性能分析',
  feedback: '告诉我们你的想法',
  survey: '反馈',
} as const
