export const COMMAND_HELPER_SUMMARIES_ZH: Record<string, string> = {
  ACL: 'ACL 访问控制命令的容器。',
  'ACL CAT': '列出 ACL 分类，或列出某个分类下的命令。',
  'ACL DELUSER': '删除 ACL 用户，并终止这些用户的连接。',
  'ACL DRYRUN': '模拟以指定用户执行命令，但不真正执行。',
  'ACL GENPASS': '生成安全的随机密码。',
  'ACL GETUSER': '返回指定 ACL 用户的规则。',
  'ACL HELP': '返回 ACL 命令的帮助信息。',
  'ACL LIST': '返回所有 ACL 用户的规则。',
  'ACL LOAD': '从 aclfile 文件重新加载 ACL 规则。',
  'ACL LOG': '列出最近的 ACL 安全事件。',
  'ACL SAVE': '将当前 ACL 规则保存到 aclfile 文件。',
  'ACL SETUSER': '修改或创建指定 ACL 用户的规则。',
  'ACL USERS': '列出所有 ACL 用户名。',
  'ACL WHOAMI': '返回当前连接正在使用的 ACL 用户名。',
  APPEND: '如果键存在就追加字符串；不存在则创建该键。',
  ASKING: '允许连接在集群迁移槽位时向目标节点发送一次请求。',
  AUTH: '使用密码，或用户名和密码进行身份验证。',
  BGREWRITEAOF: '异步重写仅追加文件。',
  BGSAVE: '异步保存数据集到磁盘。',
  BITCOUNT: '统计字符串中被设置为 1 的位数量。',
  BITFIELD: '对字符串执行任意位域整数操作。',
  BITFIELD_RO: '以只读方式对字符串执行位域整数操作。',
  BITOP: '对一个或多个字符串执行按位运算，并保存结果。',
  BITPOS: '查找字符串中第一个 0 或 1 位的位置。',
  BLPOP: '阻塞式弹出一个列表的第一个元素。',
  BMPOP: '阻塞式从一个或多个列表弹出元素。',
  BLMOVE: '阻塞式从一个列表移动元素到另一个列表。',
  BRPOP: '阻塞式弹出一个列表的最后一个元素。',
  BRPOPLPUSH: '阻塞式弹出列表尾部元素，并推入另一个列表头部。',
  BZMPOP: '阻塞式从一个或多个有序集合弹出元素。',
  BZPOPMAX: '阻塞式弹出一个或多个有序集合中分数最高的成员。',
  BZPOPMIN: '阻塞式弹出一个或多个有序集合中分数最低的成员。',
  CLIENT: '客户端连接管理命令的容器。',
  'CLIENT CACHING': '控制服务器辅助客户端缓存的跟踪模式。',
  'CLIENT GETNAME': '返回当前连接的名称。',
  'CLIENT GETREDIR': '返回当前客户端跟踪重定向的客户端 ID。',
  'CLIENT ID': '返回当前连接的唯一客户端 ID。',
  'CLIENT INFO': '返回当前客户端连接的信息。',
  'CLIENT KILL': '关闭客户端连接。',
  'CLIENT LIST': '返回客户端连接列表。',
  'CLIENT NO-EVICT': '设置当前连接在客户端淘汰机制中的处理方式。',
  'CLIENT NO-TOUCH': '控制当前连接是否更新键的最后访问时间。',
  'CLIENT PAUSE': '暂停处理客户端命令一段时间。',
  'CLIENT REPLY': '控制服务器是否向当前连接返回命令回复。',
  'CLIENT SETINFO': '设置当前客户端连接的附加信息。',
  'CLIENT SETNAME': '设置当前连接的名称。',
  'CLIENT TRACKING': '开启或关闭服务器辅助客户端缓存跟踪。',
  'CLIENT TRACKINGINFO': '返回当前连接的客户端缓存跟踪信息。',
  CLUSTER: 'Redis Cluster 管理命令的容器。',
  'CLUSTER ADDSLOTS': '将一个或多个哈希槽分配给当前节点。',
  'CLUSTER COUNTKEYSINSLOT': '返回指定哈希槽中的键数量。',
  'CLUSTER DELSLOTS': '从当前节点移除一个或多个哈希槽。',
  'CLUSTER GETKEYSINSLOT': '返回指定哈希槽中的键名。',
  'CLUSTER INFO': '返回 Redis Cluster 的状态信息。',
  'CLUSTER KEYSLOT': '返回键所属的哈希槽。',
  'CLUSTER NODES': '返回集群中所有节点的信息。',
  'CLUSTER SLOTS': '返回集群槽位到节点的映射。',
  COMMAND: '返回 Redis 命令的详细信息。',
  'COMMAND COUNT': '返回 Redis 支持的命令数量。',
  'COMMAND DOCS': '返回命令文档信息。',
  'COMMAND GETKEYS': '从完整命令中提取键名。',
  'COMMAND INFO': '返回一个或多个命令的详细信息。',
  'COMMAND LIST': '返回命令名称列表。',
  CONFIG: '服务器配置管理命令的容器。',
  'CONFIG GET': '返回配置参数的当前值。',
  'CONFIG RESETSTAT': '重置 INFO 命令统计项。',
  'CONFIG REWRITE': '重写配置文件，保留当前配置。',
  'CONFIG SET': '修改服务器配置参数。',
  COPY: '复制指定键的值到另一个键。',
  DBSIZE: '返回当前数据库中的键数量。',
  DECR: '将键中的整数值减 1。',
  DECRBY: '将键中的整数值减去指定数值。',
  DEL: '删除一个或多个键。',
  DISCARD: '放弃事务队列中的所有命令。',
  DUMP: '返回键值的序列化表示。',
  ECHO: '返回给定字符串。',
  EVAL: '执行 Lua 脚本。',
  EVALSHA: '通过 SHA1 摘要执行已缓存的 Lua 脚本。',
  EXEC: '执行事务队列中的所有命令。',
  EXISTS: '判断一个或多个键是否存在。',
  EXPIRE: '设置键的过期时间，单位为秒。',
  EXPIREAT: '设置键在指定 Unix 时间戳过期，单位为秒。',
  EXPIRETIME: '返回键的过期 Unix 时间戳，单位为秒。',
  FLUSHALL: '删除所有数据库中的所有键。',
  FLUSHDB: '删除当前数据库中的所有键。',
  GEOADD: '向地理空间索引中添加一个或多个成员。',
  GEODIST: '返回两个地理空间成员之间的距离。',
  GEOHASH: '返回一个或多个成员的 Geohash 字符串。',
  GEOPOS: '返回一个或多个地理空间成员的经纬度。',
  GEORADIUS: '查询指定圆形范围内的地理空间成员。',
  GEORADIUSBYMEMBER: '查询以指定成员为中心的圆形范围内的地理空间成员。',
  GEOSEARCH: '在地理空间索引中查询指定圆形或矩形范围内的成员。',
  GEOSEARCHSTORE: '执行地理空间范围查询，并将结果保存到目标键。',
  GET: '获取指定键的值。',
  GETBIT: '返回字符串指定偏移量上的位值。',
  GETDEL: '获取键的值，并删除该键。',
  GETEX: '获取键的值，并可同时设置过期时间。',
  GETRANGE: '返回字符串值中指定范围的子串。',
  GETSET: '设置键的新值，并返回旧值。',
  HDEL: '删除哈希中的一个或多个字段。',
  HEXISTS: '判断哈希字段是否存在。',
  HGET: '获取哈希字段的值。',
  HGETALL: '返回哈希中的所有字段和值。',
  HINCRBY: '将哈希字段的整数值增加指定数值。',
  HINCRBYFLOAT: '将哈希字段的浮点数值增加指定数值。',
  HKEYS: '返回哈希中的所有字段名。',
  HLEN: '返回哈希中的字段数量。',
  HMGET: '返回哈希中一个或多个字段的值。',
  HMSET: '设置哈希中多个字段的值。',
  HRANDFIELD: '随机返回哈希中的一个或多个字段。',
  HSCAN: '增量遍历哈希中的字段和值。',
  HSET: '设置哈希字段的字符串值。',
  HSETNX: '仅当哈希字段不存在时设置字段值。',
  HSTRLEN: '返回哈希字段值的字符串长度。',
  HVALS: '返回哈希中的所有值。',
  INCR: '将键中的整数值加 1。',
  INCRBY: '将键中的整数值增加指定数值。',
  INCRBYFLOAT: '将键中的浮点数值增加指定数值。',
  INFO: '返回服务器信息和统计数据。',
  KEYS: '查找所有匹配给定模式的键。',
  LASTSAVE: '返回最近一次成功保存到磁盘的时间。',
  LCS: '查找两个字符串之间的最长公共子序列。',
  LINDEX: '返回列表中指定索引的元素。',
  LINSERT: '在列表中指定元素前后插入新元素。',
  LLEN: '返回列表的长度。',
  LMOVE: '从一个列表移动元素到另一个列表。',
  LMPOP: '从一个或多个列表弹出元素。',
  LPOP: '弹出并返回列表的第一个元素。',
  LPOS: '返回列表中匹配元素的索引。',
  LPUSH: '将一个或多个元素推入列表头部。',
  LPUSHX: '仅当列表存在时，将元素推入列表头部。',
  LRANGE: '返回列表中指定范围的元素。',
  LREM: '从列表中删除指定数量的匹配元素。',
  LSET: '设置列表指定索引处的元素。',
  LTRIM: '裁剪列表，只保留指定范围内的元素。',
  MEMORY: '内存管理和检查命令的容器。',
  MGET: '返回一个或多个键的值。',
  MIGRATE: '将键原子性迁移到另一个 Redis 实例。',
  MONITOR: '实时打印服务器收到的所有命令。',
  MOVE: '将键移动到另一个数据库。',
  MSET: '一次设置多个键的值。',
  MSETNX: '仅当所有键都不存在时，一次设置多个键。',
  MULTI: '开启事务。',
  OBJECT: '检查 Redis 对象内部信息的命令容器。',
  PERSIST: '移除键的过期时间。',
  PEXPIRE: '设置键的过期时间，单位为毫秒。',
  PEXPIREAT: '设置键在指定 Unix 时间戳过期，单位为毫秒。',
  PEXPIRETIME: '返回键的过期 Unix 时间戳，单位为毫秒。',
  PFADD: '将元素添加到 HyperLogLog。',
  PFCOUNT: '返回 HyperLogLog 估算的基数。',
  PFMERGE: '合并多个 HyperLogLog。',
  PING: '检查服务器是否可用。',
  PSETEX: '设置键的字符串值和毫秒级过期时间。',
  PSUBSCRIBE: '订阅一个或多个符合模式的频道。',
  PTTL: '返回键的剩余过期时间，单位为毫秒。',
  PUBLISH: '向频道发布消息。',
  PUBSUB: 'Pub/Sub 子系统检查命令的容器。',
  PUNSUBSCRIBE: '退订一个或多个模式频道。',
  QUIT: '关闭当前连接。',
  RANDOMKEY: '从当前数据库随机返回一个键。',
  READONLY: '允许集群副本节点处理读请求。',
  READWRITE: '禁用集群连接的只读模式。',
  RENAME: '重命名键。',
  RENAMENX: '仅当新键不存在时重命名键。',
  REPLICAOF: '将服务器设置为另一个实例的副本，或取消复制。',
  RESTORE: '从序列化值创建键。',
  ROLE: '返回实例在复制中的角色。',
  RPOP: '弹出并返回列表的最后一个元素。',
  RPOPLPUSH: '弹出列表尾部元素，并推入另一个列表头部。',
  RPUSH: '将一个或多个元素推入列表尾部。',
  RPUSHX: '仅当列表存在时，将元素推入列表尾部。',
  SADD: '向集合添加一个或多个成员。',
  SAVE: '同步保存数据集到磁盘。',
  SCAN: '增量遍历当前数据库中的键。',
  SCARD: '返回集合的成员数量。',
  SCRIPT: 'Lua 脚本管理命令的容器。',
  SDIFF: '返回多个集合的差集。',
  SDIFFSTORE: '将多个集合的差集保存到目标键。',
  SELECT: '切换连接使用的数据库。',
  SET: '设置指定键的字符串值。',
  SETBIT: '设置字符串指定偏移量上的位值。',
  SETEX: '设置键的字符串值和秒级过期时间。',
  SETNX: '仅当键不存在时设置键的值。',
  SETRANGE: '从指定偏移量开始覆盖字符串的一部分。',
  SHUTDOWN: '同步保存数据集并关闭服务器。',
  SINTER: '返回多个集合的交集。',
  SINTERCARD: '返回多个集合交集的成员数量。',
  SINTERSTORE: '将多个集合的交集保存到目标键。',
  SISMEMBER: '判断值是否是集合成员。',
  SLAVEOF: '将服务器设置为另一个实例的副本，或取消复制。',
  SLOWLOG: '慢日志管理命令的容器。',
  SMEMBERS: '返回集合中的所有成员。',
  SMISMEMBER: '判断多个值是否是集合成员。',
  SMOVE: '将成员从一个集合移动到另一个集合。',
  SORT: '对列表、集合或有序集合中的元素排序。',
  SORT_RO: '以只读方式对列表、集合或有序集合中的元素排序。',
  SPOP: '移除并返回集合中的一个或多个随机成员。',
  SRANDMEMBER: '随机返回集合中的一个或多个成员。',
  SREM: '从集合中移除一个或多个成员。',
  SSCAN: '增量遍历集合中的成员。',
  STRLEN: '返回字符串值的长度。',
  SUBSCRIBE: '订阅一个或多个频道。',
  SUBSTR: '返回字符串值中指定范围的子串。',
  SUNION: '返回多个集合的并集。',
  SUNIONSTORE: '将多个集合的并集保存到目标键。',
  SWAPDB: '交换两个数据库。',
  TIME: '返回服务器当前时间。',
  TOUCH: '更新一个或多个键的最后访问时间。',
  TTL: '返回键的剩余过期时间，单位为秒。',
  TYPE: '返回键存储的值类型。',
  UNLINK: '异步删除一个或多个键。',
  UNSUBSCRIBE: '退订一个或多个频道。',
  UNWATCH: '取消监视所有键。',
  WAIT: '阻塞直到写入传播到指定数量的副本。',
  WATCH: '监视一个或多个键，用于事务条件执行。',
  XACK: '确认一个或多个流消息已处理。',
  XADD: '向流追加一条新消息。',
  XAUTOCLAIM: '自动转移待处理流消息的所有权。',
  XCLAIM: '转移待处理流消息的所有权。',
  XDEL: '删除一条或多条流消息。',
  XGROUP: '消费者组命令的容器。',
  'XGROUP CREATE': '创建消费者组。',
  'XGROUP CREATECONSUMER': '在消费者组中创建消费者。',
  'XGROUP DELCONSUMER': '从消费者组中删除消费者。',
  'XGROUP DESTROY': '销毁消费者组。',
  'XGROUP SETID': '设置消费者组的最后递送消息 ID。',
  XINFO: '流信息查看命令的容器。',
  XLEN: '返回流中的消息数量。',
  XPENDING: '检查消费者组中的待处理消息。',
  XRANGE: '按 ID 范围返回流消息。',
  XREAD: '从一个或多个流读取消息。',
  XREADGROUP: '通过消费者组从一个或多个流读取消息。',
  XREVRANGE: '按 ID 范围倒序返回流消息。',
  XTRIM: '裁剪流到指定长度或 ID 范围。',
  ZADD: '向有序集合添加成员，或更新已有成员的分数。',
  ZCARD: '返回有序集合的成员数量。',
  ZCOUNT: '返回有序集合中分数在指定范围内的成员数量。',
  ZDIFF: '返回多个有序集合的差集。',
  ZDIFFSTORE: '将多个有序集合的差集保存到目标键。',
  ZINCRBY: '增加有序集合中成员的分数。',
  ZINTER: '返回多个有序集合的交集。',
  ZINTERCARD: '返回多个有序集合交集的成员数量。',
  ZINTERSTORE: '将多个有序集合的交集保存到目标键。',
  ZLEXCOUNT: '返回有序集合中字典序在指定范围内的成员数量。',
  ZMPOP: '从一个或多个有序集合弹出成员。',
  ZMSCORE: '返回有序集合中一个或多个成员的分数。',
  ZPOPMAX: '移除并返回有序集合中分数最高的成员。',
  ZPOPMIN: '移除并返回有序集合中分数最低的成员。',
  ZRANDMEMBER: '随机返回有序集合中的一个或多个成员。',
  ZRANGE: '返回有序集合中指定范围的成员。',
  ZRANGEBYLEX: '返回有序集合中字典序在指定范围内的成员。',
  ZRANGEBYSCORE: '返回有序集合中分数在指定范围内的成员。',
  ZRANGESTORE: '将有序集合范围查询结果保存到目标键。',
  ZRANK: '返回有序集合中成员的排名。',
  ZREM: '从有序集合中移除一个或多个成员。',
  ZREMRANGEBYLEX: '按字典序范围移除有序集合成员。',
  ZREMRANGEBYRANK: '按排名范围移除有序集合成员。',
  ZREMRANGEBYSCORE: '按分数范围移除有序集合成员。',
  ZREVRANGE: '倒序返回有序集合中指定范围的成员。',
  ZREVRANGEBYLEX: '倒序返回有序集合中字典序在指定范围内的成员。',
  ZREVRANGEBYSCORE: '倒序返回有序集合中分数在指定范围内的成员。',
  ZREVRANK: '返回有序集合中成员的倒序排名。',
  ZSCAN: '增量遍历有序集合中的成员和分数。',
  ZSCORE: '返回有序集合中成员的分数。',
  ZUNION: '返回多个有序集合的并集。',
  ZUNIONSTORE: '将多个有序集合的并集保存到目标键。',
}

export const getCommandHelperSummary = (
  commandName: string,
  fallbackSummary = '',
) => COMMAND_HELPER_SUMMARIES_ZH[commandName.toUpperCase()] ?? fallbackSummary
