export const BROWSER_LABELS = {
  addKey: '添加键',
  bulkActions: '批量操作',
  allKeyTypes: '所有键类型',
  filterByKeyNameOrPattern: '按键名或模式筛选',
  searchByValuesOfKeys: '按键值搜索',
  results: '结果：',
  scanned: '已扫描',
  total: '总数：',
  scanning: '正在扫描...',
  lastRefresh: '上次刷新：',
  autoRefresh: '自动刷新：',
  lastRefreshTooltip: '上次刷新',
  autoRefreshConfig: '自动刷新设置',
  autoRefreshSwitch: '自动刷新',
  refreshRate: '刷新频率：',
  columns: '列',
  keySize: '键大小',
  keySizeTip: '隐藏键大小可以避免处理大型键时出现性能问题。',
  sortBy: '排序方式：',
  noLimit: '无过期',
  listView: '列表视图',
  treeView: '树形视图',
  treeViewUnavailableHex: '选择 HEX 键名格式时，树形视图不可用。',
  selectIndexToRefresh: '请选择索引后刷新键。',
  showHistory: '显示历史',
  keyCount: '个键',
  back: '返回',
  close: '关闭',
  closePanel: '关闭面板',
  bulk: {
    title: '批量操作',
    deleteKeys: '删除键',
    uploadData: '上传数据',
    noPatternOrKeyType: '未设置模式或键类型',
    noPatternOrKeyTypeDescription:
      '要执行批量操作，请先设置匹配模式或选择键类型',
    deleteKeysWith: '删除匹配以下条件的键',
    keyType: '键类型：',
    pattern: '模式：',
    inProgress: '进行中：',
    stopped: '已停止：',
    actionCompleted: '操作已完成',
    actionFailed: '操作失败',
    connectionLost: '连接丢失：',
    expectedAmount: '预计数量',
    notAvailable: 'N/A',
    keys: '个键',
    expectedAmountTooltip:
      '预计数量根据已扫描键数量和扫描百分比估算，最终数量可能不同。',
    scanned: '已扫描',
    andFound: '，找到',
    results: '结果',
    keysProcessed: '已处理键',
    commandsProcessed: '已处理命令',
    success: '成功',
    errors: '错误',
    timeTaken: '耗时',
    downloadReport: '下载报告',
    downloadReportTooltip: '下载已删除键的详细报告。',
    cancel: '取消',
    stop: '停止',
    delete: '删除',
    startNew: '重新开始',
    upload: '上传',
    uploadFileDescription: '上传包含 Redis 命令列表的文本文件',
    selectOrDropFile: '选择文件或拖拽文件到此处',
    selectOrDropFileAria: '选择或拖拽文件',
    fileTooLargePrefix: '文件不能超过',
    commandsExecutedFromFile: '从文件执行的命令',
    confirmActionTitle: '确定要执行此操作吗？',
    deleteConfirmMessage: '这将删除所有匹配所选类型和模式的键。',
    deleteImpactWarning:
      '批量删除可能影响性能并导致内存峰值。请避免在生产环境中执行。',
    deleteAllMatchingKeys: '删除所有匹配的键',
    deleteActionDescription:
      '这将删除所有匹配所选类型和模式的键。批量删除可能影响性能并导致内存峰值。',
    uploadConfirmMessage: '文件中的所有命令都会在当前数据库上执行。',
  },
} as const
